apiVersion: v2
name: api-gateway
description: ChefHub API Gateway service
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: chefhub-common
    version: "1.0.0"
    repository: "file://../common"
