apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chefhub-observability

resources:
  - namespace.yaml
  - prometheus/prometheus.yaml
  - prometheus/alerts/service-alerts.yaml
  - grafana/grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: chefhub-observability
  app.kubernetes.io/managed-by: kustomize
