apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chefhub

resources:
  # Namespaces (applied first)
  - namespace.yaml

  # Security
  - network-policies.yaml
  - resource-quotas.yaml

  # Messaging
  - rabbitmq-cluster.yaml

commonLabels:
  app.kubernetes.io/part-of: chefhub
  app.kubernetes.io/managed-by: kustomize
